name       : lemonbar
version    : 1.2
release    : 1
source     :
    - https://github.com/LemonBoy/bar/archive/v1.2.tar.gz : b846d8451f9065cdcb94f48a8bd80c074cf1073da0664a94597681912045bfea
license    : MIT
component  : desktop
summary    : A featherweight, lemon-scented, bar based on xcb
description: |
    A featherweight, lemon-scented, bar based on xcb
builddeps  :
    - pkgconfig(xcb)
build      : |
    %make
install    : |
    %make_install
