name       : lemonbar
version    : '1.3'
release    : 3
source     :
    - https://github.com/LemonBoy/bar/archive/v1.3.tar.gz : eae784c5e375b2d0b12138be1a9902beb4b5eeb807f3512f30f14ba23ddaa37d
license    : MIT
component  : desktop
summary    : A featherweight, lemon-scented, bar based on xcb
description: |
    A featherweight, lemon-scented, bar based on xcb
builddeps  :
    - pkgconfig(xcb)
rundeps    :
    - xtitle
build      : |
    %make
install    : |
    %make_install
